name: "Build app"

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]

    runs-on: ubuntu-latest

    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Pulling code
        uses: actions/checkout@v2

      - name: Build
        run: go build ./...
